/* This file is generated by code_gen.py */
#ifndef __SCHEMA_H__
#define __SCHEMA_H__
	struct frames {
		float f_feature[2048];
		char video_name[23];
	};

    struct video {
		float v_feature[2048];
	};

    struct object {
        float o_feature[2048];
    };

	struct sift {
		int s_id;
		float s_feature[128];
	};

	struct search {
		float s_feature[2048];
	};

	struct dataset {
		float d_feature[2048];
		char video_name[23];
	};

#endif
